apiVersion: v1
kind: Service
metadata:
  name: {{ include "miningcore.fullname" . }}-miningcore-api
  labels:
    {{- include "miningcore.common.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.common.apiPort }}
      targetPort: {{ .Values.common.apiPort }}
      protocol: TCP
      name: mc-api
  selector:
    {{- include "miningcore.common.matchLabels" . | nindent 4 }}
