apiVersion: v1
kind: Service
metadata:
  name: {{ include "miningcore.stratum.fullname" . }}
  labels:
    {{- include "miningcore.stratum.labels" . | nindent 4 }}
spec:
  type: {{ .Values.stratum.service.type }}
  ports:
    {{- range .Values.stratum.stratum_ports }}
    - port: {{ .containerPort }}
      targetPort: {{ .containerPort }}
      protocol: TCP
      nodePort: {{ .nodePort }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "miningcore.stratum.matchLabels" . | nindent 4 }}
