{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "miningcore.fullname" . }}
  labels:
    {{- include "miningcore.common.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "miningcore.common.matchLabels" . | nindent 6 }}
  endpoints:
    - port: mc-api
      relabelings:
        - action: replace
          replacement: {{ .Values.common.clusterName }}
          targetLabel: cluster
        - action: replace
          replacement: {{ .Values.common.env }}
          targetLabel: miningcore
  namespaceSelector:
    any: true
{{- end }}