{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "phantomias.fullname" . }}
  labels:
    {{- include "phantomias.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "phantomias.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
  namespaceSelector:
    any: true
{{- end }}