{{- if .Values.payout.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "miningcore.payout.fullname" . }}
  labels:
    {{- include "miningcore.payout.labels" . | nindent 4 }}
spec:
  {{- with .Values.payout.podDisruptionBudget.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  {{- with .Values.payout.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "miningcore.payout.matchLabels" . | nindent 6 }}
{{- end }}
