apiVersion: v2
name: miningcore
description: A Helm chart for miningcore
type: application
version: 1.1.1
appVersion: "2.7.0"
dependencies:
- name: postgresql
  version: 12.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled