{{- if .Values.stratum.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "miningcore.stratum.fullname" . }}
  labels:
    {{- include "miningcore.stratum.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "miningcore.stratum.fullname" . }}
  minReplicas: {{ .Values.stratum.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.stratum.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.stratum.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.stratum.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
    {{- if .Values.stratum.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.stratum.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
  behavior: {{ .Values.stratum.autoscaling.behavior | toYaml | nindent 4}}
{{- end }}
