{{- if .Values.stats.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "miningcore.stats.fullname" . }}
  labels: 
    {{- include "miningcore.stats.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.stats.replicaCount }}
  selector:
    matchLabels:
      {{- include "miningcore.stats.matchLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.stats.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "miningcore.stats.matchLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.stats.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ template "miningcore.name" . }}-{{ .Values.stats.name }}
          securityContext:
            {{- toYaml .Values.stats.securityContext | nindent 12 }}
          image: "{{ .Values.stats.image.repository }}:{{ .Values.stats.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.stats.image.pullPolicy }}
          env:
            - name: MC_CLUSTERNAME
              value: {{ .Values.common.clusterName | quote }}
            {{- if .Values.postgresql.enabled }}
            - name: MC_PERSISTENCE_HOST
              value: {{ include "postgresql.primary.fullname" .Subcharts.postgresql | quote }}
            - name: MC_PERSISTENCE_PORT
              value: {{ include "postgresql.service.port" .Subcharts.postgresql | int }}
            - name: MC_PERSISTENCE_USER
              value: {{ include "postgresql.username" .Subcharts.postgresql | quote }}
            - name: MC_PERSISTENCE_DATABASE
              value: {{ include "postgresql.database" .Subcharts.postgresql | quote }}
            {{- else }}
            - name: MC_PERSISTENCE_HOST
              value: {{ .Values.externalDatabase.host | quote }}
            - name: MC_PERSISTENCE_PORT
              value: {{ .Values.externalDatabase.port | quote }}
            - name: MC_PERSISTENCE_USER
              value: {{ .Values.externalDatabase.user | quote }}
            - name: MC_PERSISTENCE_DATABASE
              value: {{ .Values.externalDatabase.database | quote }}
            {{- end }}
            - name: MC_PERSISTENCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "miningcore.postgresql.secret" . | quote }}
                  key: {{ include "miningcore.postgresql.secretKey" . | quote }}
            {{- if .Values.stats.poolEndpointTLSPFXPasswordSecret }}
            - name: MC_POOL_ENDPOINT_TLS_PFX_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.stats.poolEndpointTLSPFXPasswordSecret | quote }}
                  key: tlsPfxPassword
            {{- end }}
          ports:
            - name: mc-api
              containerPort: {{ .Values.common.apiPort }}
          volumeMounts:
            - name: config
              mountPath: /app/config.json
              subPath: config.json
            {{- if .Values.stats.poolEndpointTLSPFXPasswordSecret }}
            - name: pool-endpoint-tls-pfx
              mountPath: /app/pool-endpoint-tls.pfx
              subPath: tlsPfxFile
            {{- end }}
          resources:
            {{- toYaml .Values.stats.resources | nindent 12 }}
          livenessProbe:
            initialDelaySeconds: 20
            tcpSocket:
              port: {{ .Values.common.apiPort }}
          readinessProbe:
            initialDelaySeconds: 20
            tcpSocket:
              port: {{ .Values.common.apiPort }}
      volumes:
        - name: config
          configMap:
            name: {{ include "miningcore.stats.fullname" . }}-config
        {{- if .Values.stats.poolEndpointTLSPFXPasswordSecret }}
        - name: pool-endpoint-tls-pfx
          secret:
            secretName: {{ .Values.stats.poolEndpointTLSPFXPasswordSecret | quote }}
        {{- end }}
      {{- with .Values.stats.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stats.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}